### PR TITLE
Fire the $onInit lifecycle hook

### LINKED ISSUE #173: Implement $onInit hook?
Some 3rd party libraries that instantiate controllers, like ui-router, have chosen to implement the `$onInit` hook so that controllers can be more easily reused between components and other places. Is this something that would be a considered feature for angular-modal-service?

### PR DESCRIPTION
**Pull request by jpulec**
This PR makes the modal controller fire the [$onInit](https://code.angularjs.org/1.6.0/docs/api/ng/service/$compile) lifecycle hook that is often associated with angular component controllers. By implementing this hook, controllers can more easily be reused between ModalService and other uses.

As one example, ui-router chose to implement the $onInit hook to ease controller reusability.

Closes #173

### CODE REVIEW

**Comment by elliottregan** [comment]
I'd love to help get this in. Looks like it just needs a rebase?

**Comment by dwmkerr** [comment]
@elliottregan that's right, should be good after a rebase (just the usual hassle of dealing with the `dst` files!)

**Comment by jpulec** [comment]
Rebased!

**Comment by dwmkerr** [comment]
Resolved with #257, release in `0.15.1`, sorry for the delay and thanks for raising!

**Comment by elliottregan** [comment]
Thanks for continuing to support this! This is still my favorite modal solution for any framework at the moment.

**Comment by dwmkerr** [comment]
My pleasure! If you are interested in collaborating on a version for the more recent releases of angular let me know!

**Pull request closed without merging**
