### PR TITLE
Remove coverage stuff from build output

### PR DESCRIPTION
**Pull request by StormPooper**
So after my last pull request was accepted (thanks again for that) and we went to update to the latest version, we started getting errors in our build environment.

Digging into it, it turns out that the coverage test stuff was being included within the actual distribution files, which our build server started to panic over. To prevent this, I've moved the isparta-loader to only be included when running karma tests, as this prevents the dst files being created with coverage within them but still generates the coverage report.

@dwmkerr - I've tested this out with each npm script included and it appears to work for me, but I'm no webpack expert, so if you'd prefer to make changes or just close the pull request and update it yourself it's not a problem. GitHub collapses the dst files by default, but if you expand them you'll see that there is no more coverage stuff in there.

### CODE REVIEW

**Comment by dwmkerr** [comment]
Hi Daniel, OK cool thanks for such a speedy update! Let me clone the PR, run the tests locally and then I'll rush out a release to patch this issue

**Comment by StormPooper** [comment]
Thanks Dave, if you need to make any changes you should be able to push to my branch and include it in the pull request, go right ahead.

**Comment by StormPooper** [comment]
Hi @dwmkerr, did you get a chance to look this over?

**Comment by StormPooper** [comment]
Hey @dwmkerr, sorry to bother you, but did you get a chance to try out the changes?

**Comment by dwmkerr** [comment]
Hi @StormPooper sorry for the delay, been a little ill the last few days! I've just merged, tested, pushed and released, this is now in the latest version, 0.11.1. Thanks again!

**Comment by StormPooper** [comment]
No problem, I get how it is, thanks very much!

**Pull request merged**
