### PR TITLE
Update sampleapp.js

### PR DESCRIPTION
**Pull request by FlavorScape**
The latest version of bootstrap changed modal() to show() on the Modal object's prototype

### CODE REVIEW

**Comment by dwmkerr** [comment]
Hi @FlavorScape does this also necessitate a change to the dependencies to make sure we grab the right bootstrap for the change? I think we'd need to update the bower.json file and rebuild the vendor files (see `gulp vendor` which will update the files!)

**Comment by FlavorScape** [comment]
Yeah I think bower should update. I encountered this pretty early, I wonder if there's other bootstrap breaking changes. Also, I found that I had to add ng-if="isCollapsed" to get the small nav to actually hide when hamburger is clicked.... this was not in the example, so maybe this is breaking with BS as well.

<nav class="visible-xs" collapse="!isCollapsed" ng-if="!isCollapsed">

**Comment by dwmkerr** [comment]
Hi @FlavorScape I might be missing something but it looks like it's still `modal` in the docs:

http://getbootstrap.com/javascript/#modals

**Comment by hackzilla** [comment]
Related: #84

**Comment by dwmkerr** [comment]
Closing this PR, currently the docs state that `modal` is the appropriate function to use.

**Pull request closed without merging**
