### PR TITLE
LocationChangeSuccess event registration to be configurable

### PR DESCRIPTION
**Pull request by smalbs**
There's two issues (#172 and #164) where the locationChangeSuccess event listener is registered immediately causing a problem for any pending route changes.  This update allows the locationChangeSuccess to be configurable as a part of he showModal options:
- default (no option) will register listener immedieately
- false will disable event registration
- number >= 0 will register event after delay

### CODE REVIEW

**Comment by pdemilly** [comment]
I just tried your branch and it fixed the problem I was having. Thanks. 

+1 to merge it

**Comment by samalbert** [comment]
@pdemilly Glad I could help!

**Comment by SergeyCherman** [comment]
@dwmkerr can this be merged and a version bump be made?

**Comment by dkozickis** [comment]
Can this be merged please?

**Comment by smalbs** [comment]
@dkozickis this has been open for a year. project seems to be left for dead :(

but you can install my fork directly: https://github.com/samalbert/angular-modal-service/archive/v0.11.2.tar.gz

**Comment by dkozickis** [comment]
@smalbs already did, thank you!

**Comment by dwmkerr** [comment]
Hey guys sorry will get on this as soon as possible, have had a whole bunch of things at work to look into, will see if I can merge this today

**Comment by smalbs** [comment]
thx, @dwmkerr.  great library here...  you should be good to close tickets #172 and #164

**Comment by dwmkerr** [comment]
No worries! I added you to the CHANGELOG, also updated the README with docs on how to use the new option, thanks for the PR and apologies for the delay

**Pull request merged**
