### PR TITLE
Avoid open multiple modal on press enter

### PR DESCRIPTION
**Pull request by samwx**

### CODE REVIEW

**Comment by dwmkerr** [comment]
This looks really smart, I have one question though - if there is no active element will this additional line throw an exception?

**Comment by samwx** [comment]
@dwmkerr Nope! It will returns "undefined", and not an exception :)

**Comment by samwx** [comment]
@dwmkerr =(

**Comment by dwmkerr** [comment]
OK cool merging now! sorry for the delay

**Comment by dwmkerr** [comment]
I've released `v0.12.3` and added you to the contributors, thanks!

**Pull request merged**
