### PR TITLE
Feature/utilize provider

### PR DESCRIPTION
**Pull request by decherneyge**
Added the framework for default configuration options. Setup a global option for closeDelay

### CODE REVIEW

**Comment by dwmkerr** [comment]
Awesome - are you OK to update from `master`? I just merged your first PR

**Comment by decherneyge** [comment]
@dwmkerr I merged master into the feature branch. Should be good now. Thanks!

**Comment by dwmkerr** [comment]
Excellent, thanks so ,much @decherneyge! I'm merging now, then will cut a new release. Thanks for these updates!

**Comment by decherneyge** [comment]
Awesome! Thanks!

**Pull request merged**
