### PR TITLE
fix ngForm issue

### PR DESCRIPTION
**Pull request by kernowjoe**
changed the order of controller creation and template compile to fix issue with ng form not being available in the controller

### CODE REVIEW

**Comment by dwmkerr** [comment]
@kernowjoe can you do a PR with just the ngForm issue fixed so I can keep the changes small? Then a separate PR for other improvements?

**Comment by kernowjoe** [comment]
@dwmkerr I had merged this back with master prior to making this pr, so should only include the ngForm issue in 2 commits

**Comment by jpulec** [comment]
Any idea where the status is on this?

**Comment by dwmkerr** [comment]
@jpulec @kernowjoe there are too many changes in this PR due to indentation etc, please re-create the PR with only the logical changes and I will endeavour to update the codebase with better linting results.

**Comment by kernowjoe** [comment]
I will endeavour to recreate and test this with the latest updated code over the weekend, I had previously made many changes and hoped to roll back to match up, it apparently didn't work to well :)

I'll create a new PR with only the change mentioned above

**Comment by kernowjoe** [comment]
Took a look this last night, the fix has already pushed from a previous commit.

**Comment by jpulec** [comment]
@kernowjoe Yeah. I saw that from a different PR. Thanks for the heads up!

**Comment by dwmkerr** [comment]
Cheers guys Glad it's worked out!!

**Pull request closed without merging**
