### PR TITLE
Ability to add custom class to body

### PR DESCRIPTION
**Pull request by StormPooper**
We're not using Bootstrap, but still wanted to be able to reap the benefits of having a `modal-open` class on the body, so I've added the `bodyClass` property - if specified, the class will be added to the body on open and removed from the body on close. I've also updated the readme and the custom modal in the sample app to use this.

### CODE REVIEW

**Comment by dwmkerr** [comment]
Hi @StormPooper like the code looks great but I think there is a bug, if the `appendElement` option is used, then the `bodyClass` should be added to that element, but instead it's added to `body` instead. Suggest renaming `bodyClass` to `appendElementClass` and supporting it on either the `body` or `appendElement`, depending on what element is selected, WDYT?

**Comment by StormPooper** [comment]
Hi @dwmkerr, I had originally considered doing that, but I decided that it was more useful to always be appended to the body as it will enable you to do things like fade the page background out while still appending the element to some child within the page. I can modify it to appendElementClass if you'd prefer though.

**Comment by StormPooper** [comment]
Hi @dwmkerr, I've updated my branch with the latest changes from master, to avoid any merge conflicts. Any thoughts on my previous comment?

**Comment by StormPooper** [comment]
Hi @dwmkerr, any thoughts on my previous comment? I can update the branch if you're happy with it so it can be merged in.

**Comment by dwmkerr** [comment]
Hi @StormPooper sorry for the delay, yes if you can update I'll merge and release ASAP!

**Comment by StormPooper** [comment]
@dwmkerr no problem, I forgot about it too :) I've updated my branch to match master and also updated the tests to ES6, so it should be good to go if you're happy with it.

**Comment by dwmkerr** [comment]
Sorry to be a pain on this one @StormPooper would you mind changing the main code file so that the diff is smaller? I think the issue is perhaps the spacing or indentation, but it's really difficult to see where the key changes are. We can fix the indentation in a separate PR which would then be easier to follow (just don't want to inadvertently miss anything from this!)

**Comment by StormPooper** [comment]
Sorry @dwmkerr, I thought I had done that but I must have made an additional change to the file before committing, it's now just the changes.

**Comment by dwmkerr** [comment]
Looks great! Will merge, update the contributor and release notes and release now :)

**Comment by StormPooper** [comment]
Awesome, thanks @dwmkerr :)

**Comment by dwmkerr** [comment]
No, thanks to you, it's a great feature! Awesome to see the changes in the samples as well!

**Comment by dwmkerr** [comment]
done and done
- https://github.com/dwmkerr/angular-modal-service/releases
- https://twitter.com/dwmkerr/status/838364578983505921

Thanks again!

**Comment by StormPooper** [comment]
Thanks :)

**Pull request merged**
